from AgentCrew.modules.llm.types import Model

COMMANDCODE_MODELS = [
    Model(
        id="claude-sonnet-4-6",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Sonnet 4.6",
        description="Anthropic Claude Sonnet 4.6 via CommandCode — advanced agentic coding and reasoning with vision and extended thinking",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        default=True,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4-8",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Opus 4.8",
        description="Anthropic Claude Opus 4.8 via CommandCode — maximum intelligence for specialized reasoning and complex agentic workflows",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4-7",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Opus 4.7",
        description="Anthropic Claude Opus 4.7 via CommandCode — maximum intelligence for specialized reasoning and complex agentic workflows",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="claude-haiku-4-5-20251001",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Haiku 4.5",
        description="Anthropic Claude Haiku 4.5 via CommandCode — fast and efficient near-frontier intelligence",
        capabilities=["tool_use", "vision", "stream"],
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.5",
        provider="commandcode",
        name="GPT-5.5",
        description="OpenAI GPT-5.5 via CommandCode — flagship model with vision, reasoning, and structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4",
        provider="commandcode",
        name="GPT-5.4",
        description="OpenAI GPT-5.4 via CommandCode — balanced performance with vision, reasoning, and structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.3-codex",
        provider="commandcode",
        name="GPT-5.3 Codex",
        description="OpenAI GPT-5.3 Codex via CommandCode — code-optimized model with reasoning and structured output",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4-mini",
        provider="commandcode",
        name="GPT-5.4 Mini",
        description="OpenAI GPT-5.4 Mini via CommandCode — fast and cost-effective model for simpler tasks",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="commandcode",
        name="Kimi K2.6",
        description="MoonshotAI Kimi K2.6 via CommandCode — vision-capable reasoning model with structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="commandcode",
        name="Kimi K2.5",
        description="MoonshotAI Kimi K2.5 via CommandCode — vision-capable reasoning model with structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="commandcode",
        name="GLM-5.1",
        description="Z.ai GLM-5.1 via CommandCode — long-context reasoning model optimized for agentic workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="zai-org/GLM-5",
        provider="commandcode",
        name="GLM-5",
        description="Z.ai GLM-5 via CommandCode — efficient model for agentic and coding workloads",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M3",
        provider="commandcode",
        name="MiniMax M3",
        description="MiniMax M3 via CommandCode — coding and agentic model with reasoning support",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.7",
        provider="commandcode",
        name="MiniMax M2.7",
        description="MiniMax M2.7 via CommandCode — coding and agentic model with reasoning support",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.5",
        provider="commandcode",
        name="MiniMax M2.5",
        description="MiniMax M2.5 via CommandCode — efficient coding and agentic model",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="deepseek/deepseek-v4-pro",
        provider="commandcode",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro via CommandCode — advanced reasoning model for complex agentic workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="deepseek/deepseek-v4-flash",
        provider="commandcode",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash via CommandCode — fast lower-latency model for agentic and coding workloads",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="Qwen/Qwen3.6-Max-Preview",
        provider="commandcode",
        name="Qwen3.6 Max Preview",
        description="Qwen3.6 Max Preview via CommandCode — reasoning and agentic model for complex workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="Qwen/Qwen3.6-Plus",
        provider="commandcode",
        name="Qwen3.6 Plus",
        description="Qwen3.6 Plus via CommandCode — efficient reasoning model for agentic and coding tasks",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="Qwen/Qwen3.7-Max",
        provider="commandcode",
        name="Qwen3.7 Max",
        description="Qwen3.7 Max via CommandCode — agent-first flagship model for coding, reasoning, and long-horizon AI workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="Qwen/Qwen3.7-Plus",
        provider="commandcode",
        name="Qwen3.7 Plus",
        description="Qwen3.7 Plus via CommandCode — high-performance reasoning model for agentic and coding workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="stepfun/Step-3.7-Flash",
        provider="commandcode",
        name="Step 3.7 Flash",
        description="StepFun Step 3.7 Flash via CommandCode — reasoning-capable MoE model optimized for agentic and coding workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="stepfun/Step-3.5-Flash",
        provider="commandcode",
        name="Step 3.5 Flash",
        description="StepFun Step 3.5 Flash via CommandCode — sparse MoE model with frontier reasoning and agentic capabilities at 11B active parameters",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="xiaomi/mimo-v2.5-pro",
        provider="commandcode",
        name="MiMo V2.5 Pro",
        description="Xiaomi MiMo V2.5 Pro via CommandCode — reasoning-capable model optimized for agentic and coding workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="xiaomi/mimo-v2.5",
        provider="commandcode",
        name="MiMo V2.5",
        description="Xiaomi MiMo V2.5 via CommandCode — efficient model for general-purpose agentic and coding tasks",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="google/gemini-3.5-flash",
        provider="commandcode",
        name="Gemini 3.5 Flash",
        description="Google Gemini 3.5 Flash via CommandCode — vision-capable reasoning model balanced for speed and intelligence",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="google/gemini-3.1-flash-lite",
        provider="commandcode",
        name="Gemini 3.1 Flash Lite",
        description="Google Gemini 3.1 Flash Lite via CommandCode — lightweight model for cost-effective high-throughput tasks",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
]
