from AgentCrew.modules.llm.types import Model

CROFAI_MODELS = [
    Model(
        id="deepseek-v3.2",
        provider="crofai",
        name="DeepSeek V3.2",
        description="DeepSeek V3.2 on CrofAI, served through the OpenAI-compatible chat completions API.",
        capabilities=["tool_use", "stream", "structured_output"],
        default=True,
        max_context_token=163_840,
    ),
    Model(
        id="deepseek-v4-pro",
        provider="crofai",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro on CrofAI for agentic and reasoning workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
    ),
    Model(
        id="deepseek-v4-pro-precision",
        provider="crofai",
        name="DeepSeek V4 Pro Precision",
        description="DeepSeek V4 Pro Precision on CrofAI for higher precision reasoning workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
    ),
    Model(
        id="deepseek-v4-flash",
        provider="crofai",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash on CrofAI for lower-latency agentic workloads.",
        capabilities=["tool_use", "stream", "structured_output"],
    ),
    Model(
        id="glm-5.1",
        provider="crofai",
        name="GLM 5.1",
        description="Z.ai GLM 5.1 on CrofAI, optimized for long-context agentic workloads.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=202_752,
    ),
    Model(
        id="glm-5.1-precision",
        provider="crofai",
        name="GLM 5.1 Precision",
        description="Z.ai GLM 5.1 Precision on CrofAI with higher precision serving.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=202_752,
    ),
    Model(
        id="greg",
        provider="crofai",
        name="Greg",
        description="Experimental Greg model on CrofAI.",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=200_000,
    ),
    Model(
        id="kimi-k2.6-precision",
        provider="crofai",
        name="Kimi K2.6 Precision",
        description="MoonshotAI Kimi K2.6 Precision on CrofAI with vision and reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
    Model(
        id="kimi-k2.5",
        provider="crofai",
        name="Kimi K2.5",
        description="MoonshotAI Kimi K2.5 on CrofAI with vision and reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
    Model(
        id="kimi-k2.5-lightning",
        provider="crofai",
        name="Kimi K2.5 Lightning",
        description="MoonshotAI Kimi K2.5 Lightning on CrofAI with vision and custom reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=131_072,
    ),
    Model(
        id="glm-5",
        provider="crofai",
        name="GLM 5",
        description="Z.ai GLM 5 on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=202_752,
    ),
    Model(
        id="glm-4.7",
        provider="crofai",
        name="GLM 4.7",
        description="Z.ai GLM 4.7 on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=202_752,
    ),
    Model(
        id="glm-4.7-flash",
        provider="crofai",
        name="GLM 4.7 Flash",
        description="Z.ai GLM 4.7 Flash on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=202_752,
    ),
    Model(
        id="gemma-4-31b-it",
        provider="crofai",
        name="Gemma 4 31B IT",
        description="Google Gemma 4 31B instruction-tuned model on CrofAI with reasoning support.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
    Model(
        id="minimax-m2.5",
        provider="crofai",
        name="MiniMax M2.5",
        description="MiniMax M2.5 on CrofAI for coding and agentic workflows.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=204_800,
    ),
    Model(
        id="mimo-v2.5-pro",
        provider="crofai",
        name="Mimo V2.5 Pro",
        description="Mimo V2.5 Pro on CrofAI for agentic workflows.",
        capabilities=["tool_use", "stream", "structured_output"],
    ),
    Model(
        id="mimo-v2.5-pro-precision",
        provider="crofai",
        name="Mimo V2.5 Pro Precision",
        description="Mimo V2.5 Pro Precision on CrofAI for higher precision agentic workflows.",
        capabilities=["tool_use", "stream", "structured_output"],
    ),
    Model(
        id="qwen3.5-397b-a17b",
        provider="crofai",
        name="Qwen3.5 397B A17B",
        description="Qwen3.5 397B A17B on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
    Model(
        id="qwen3.5-9b",
        provider="crofai",
        name="Qwen3.5 9B",
        description="Qwen3.5 9B on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
    Model(
        id="qwen3.5-9b-chat",
        provider="crofai",
        name="Qwen3.5 9B Chat",
        description="Qwen3.5 9B Chat on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
    ),
]
