from AgentCrew.modules.llm.types import Model, SampleParam

FIREWORKS_MODELS = [
    Model(
        id="accounts/fireworks/models/deepseek-v4-pro",
        provider="fireworks",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro on Fireworks - MoE model with 1.6T total parameters and advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default=True,
        input_token_price_1m=1.74,
        cached_token_price_1m=0.15,
        output_token_price_1m=3.48,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k2p6",
        provider="fireworks",
        name="Kimi K2.6",
        description="Kimi K2.6 on Fireworks - native multimodal agentic model",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.95,
        cached_token_price_1m=0.16,
        output_token_price_1m=4.0,
    ),
    Model(
        id="accounts/fireworks/models/minimax-m2p7",
        provider="fireworks",
        name="MiniMax M2.7",
        description="MiniMax M2.7 on Fireworks - efficient agentic model with tool use and structured output",
        capabilities=["tool_use", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.3,
        cached_token_price_1m=0.06,
        output_token_price_1m=1.2,
    ),
    Model(
        id="accounts/fireworks/models/qwen3p6-plus",
        provider="fireworks",
        name="Qwen 3.6 Plus",
        description="Qwen 3.6 Plus on Fireworks - latest Qwen MoE model with reasoning capabilities",
        capabilities=["tool_use", "thinking", "structured_output", "stream", "vision"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=1,
            top_k=40,
        ),
        input_token_price_1m=0.5,
        cached_token_price_1m=0.1,
        output_token_price_1m=3.0,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p1",
        provider="fireworks",
        name="GLM 5.1",
        description="GLM-5.1 on Fireworks - Z-AI flagship model for agentic engineering",
        capabilities=["tool_use", "stream", "structured_output"],
        force_sample_params=SampleParam(top_p=1, top_k=40),
        input_token_price_1m=1.4,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.4,
    ),
    Model(
        id="accounts/fireworks/models/gemma-4-31b-it",
        provider="fireworks",
        name="Gemma 4 31B",
        description="Gemma 4 31B on Fireworks - lightweight open model from Google",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.2,
        output_token_price_1m=0.5,
    ),
]
