from AgentCrew.modules.llm.types import Model, SampleParam

GITHUB_COPILOT_MODELS = [
    Model(
        id="claude-haiku-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude 4.5 Haiku",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-2.5-pro",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 2.5 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3-pro-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3.1-pro-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3.1 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3-flash-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3 Flash Preview",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-4o",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 4o",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.1 Codex Max",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5-mini",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=264_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5.1",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=264_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="goldeneye-free-auto",
        provider="github_copilot",
        service_name="copilot_response",
        name="Goldeneye",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.2-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.3-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4-mini",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.5",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.5",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-mini",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="raptor-mini-tertiary",
        provider="github_copilot",
        service_name="github_copilot",
        name="Raptor mini",
        max_context_token=264_000,
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=True,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.5 (Preview)",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.7",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.7",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]
