from AgentCrew.modules.llm.types import Model, SampleParam

OPENCODE_GO_MODELS = [
    Model(
        id="glm-5.1",
        provider="opencode_go",
        name="GLM-5.1",
        description="OpenCode Go curated GLM-5.1 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "stream"],
        max_context_token=205_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="glm-5",
        provider="opencode_go",
        name="GLM-5",
        description="OpenCode Go curated GLM-5 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "stream"],
        max_context_token=205_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="kimi-k2.5",
        provider="opencode_go",
        name="Kimi K2.5",
        description="OpenCode Go curated Kimi K2.5 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "vision", "structured_output", "stream"],
        default=True,
        max_context_token=265_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="kimi-k2.6",
        provider="opencode_go",
        name="Kimi K2.6",
        description="OpenCode Go curated Kimi K2.6 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "vision", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="kimi-k2.7-code",
        provider="opencode_go",
        name="Kimi K2.7 Code",
        description="OpenCode Go curated Kimi K2.7 Code model over the OpenAI-compatible chat completions endpoint — coding-focused with improved long-horizon coding and 30% fewer thinking tokens",
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        capabilities=["tool_use", "thinking", "vision", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2-pro",
        provider="opencode_go",
        name="MiMo-V2-Pro",
        description="OpenCode Go curated MiMo-V2-Pro model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "stream"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2-omni",
        provider="opencode_go",
        name="MiMo-V2-Omni",
        description="OpenCode Go curated MiMo-V2-Omni model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "vision", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2.5-pro",
        provider="opencode_go",
        name="MiMo-V2.5 Pro",
        description="OpenCode Go curated MiMo-V2.5 Pro model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "vision", "stream"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2.5",
        provider="opencode_go",
        name="MiMo-V2.5",
        description="OpenCode Go curated MiMo-V2.5 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "vision", "stream"],
        max_context_token=256_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="qwen3.5-plus",
        provider="opencode_go",
        name="Qwen3.5 Plus",
        description="OpenCode Go curated Qwen3.5 Plus model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "vision", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="qwen3.6-plus",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="Qwen3.6 Plus",
        description="OpenCode Go curated Qwen3.6 Plus model over the Anthropic-compatible messages endpoint",
        capabilities=["tool_use", "vision", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="qwen3.7-max",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="Qwen3.7 Max",
        description="OpenCode Go curated Qwen3.7 Max model over the Anthropic-compatible messages endpoint",
        capabilities=["tool_use", "vision", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="minimax-m3",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="MiniMax M3",
        description="OpenCode Go curated MiniMax M3 model over the Anthropic-compatible messages endpoint",
        capabilities=["tool_use", "vision", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="minimax-m2.7",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="MiniMax M2.7",
        description="OpenCode Go curated MiniMax M2.7 model over the Anthropic-compatible messages endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="minimax-m2.5",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="MiniMax M2.5",
        description="OpenCode Go curated MiniMax M2.5 model over the Anthropic-compatible messages endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="deepseek-v4-pro",
        provider="opencode_go",
        name="DeepSeek V4 Pro",
        description="OpenCode Go curated DeepSeek V4 Pro model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="deepseek-v4-flash",
        provider="opencode_go",
        name="DeepSeek V4 Flash",
        description="OpenCode Go curated DeepSeek V4 Flash model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "structured_output", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="hy3-preview",
        provider="opencode_go",
        name="HY3 Preview",
        description="OpenCode Go curated HY3 Preview model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "stream"],
        max_context_token=262_144,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]
