from .types import Model, SampleParam

_ANTHROPIC_MODELS = [
    Model(
        id="claude-opus-4-5",
        provider="claude",
        name="Claude 4.5 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=5.0,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-6",
        provider="claude",
        name="Claude 4.6 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=5.0,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-7",
        provider="claude",
        name="Claude 4.7 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=5.0,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-1",
        provider="claude",
        name="Claude 4.1 Opus",
        description="Exceptional model for specialized reasoning tasks",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=15.0,
        output_token_price_1m=75.0,
    ),
    Model(
        id="claude-sonnet-4-5",
        provider="claude",
        name="Claude 4.5 Sonnet",
        description="Our smartest model for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=3.0,
        output_token_price_1m=15.0,
    ),
    Model(
        id="claude-sonnet-4-6",
        provider="claude",
        name="Claude 4.6 Sonnet",
        description="Our smartest model for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=3.0,
        output_token_price_1m=15.0,
    ),
    Model(
        id="claude-haiku-4-5",
        provider="claude",
        name="Claude 4.5 Haiku",
        description="Our fastest model with near-frontier intelligence",
        max_context_token=200_000,
        capabilities=["tool_use", "vision", "stream", "thinking"],
        input_token_price_1m=0.8,
        output_token_price_1m=4.0,
    ),
]

_OPENAI_MODELS = [
    Model(
        id="gpt-5",
        provider="openai",
        service_name="openai_response",
        name="GPT-5",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
        default=True,
    ),
    Model(
        id="gpt-5-codex",
        provider="openai",
        service_name="openai_response",
        name="GPT-5 Codex",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.1",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.2",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.2",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.4",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.4",
        default_reasoning="high",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=1_050_000,
        input_token_price_1m=2.5,
        output_token_price_1m=15,
    ),
    Model(
        id="gpt-5.1-codex",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.1-codex-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex Mini",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=0.25,
        output_token_price_1m=2.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex Max",
        description="GPT‑5.1-Codex-Max is purpose-built for agentic coding",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10.0,
    ),
    Model(
        id="gpt-4.1-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT-4.1 Mini",
        description="small, quick GPT model",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.15,
        output_token_price_1m=0.6,
    ),
    Model(
        id="gpt-4.1",
        provider="openai",
        service_name="openai_response",
        name="GPT-4.1",
        description="Flagship model for complex tasks. It is well suited for problem solving across domains",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=2,
        output_token_price_1m=8,
    ),
    Model(
        id="o3-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT o3 mini",
        description="Fast, flexible, intelligent reasoning model",
        capabilities=["thinking", "stream", "structured_output"],
        input_token_price_1m=1.1,
        output_token_price_1m=4.4,
    ),
    Model(
        id="o4-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT o4 mini",
        description="o4-mini is our latest small o-series model. It's optimized for fast, effective reasoning with exceptionally efficient performance in coding and visual tasks.",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=1.1,
        output_token_price_1m=4.4,
    ),
    Model(
        id="o3",
        provider="openai",
        service_name="openai_response",
        name="GPT o3",
        description="a well-rounded and powerful model across domains. It sets a new standard for math, science, coding, and visual reasoning tasks. ",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=2.0,
        output_token_price_1m=8.0,
    ),
]

_OPENAI_CODEX_MODELS = [
    Model(
        id="gpt-5-codex",
        provider="openai_codex",
        name="GPT-5 Codex (ChatGPT)",
        description="GPT-5-Codex via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        default=True,
    ),
    Model(
        id="gpt-5.1-codex",
        provider="openai_codex",
        name="GPT-5.1 Codex (ChatGPT)",
        description="GPT-5.1-Codex via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-mini",
        provider="openai_codex",
        name="GPT-5.1 Codex Mini (ChatGPT)",
        description="GPT-5.1-Codex-Mini via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.2-codex",
        provider="openai_codex",
        name="GPT-5.2 Codex (ChatGPT)",
        description="GPT-5.2-Codex via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.3-codex",
        provider="openai_codex",
        name="GPT-5.3 Codex (ChatGPT)",
        description="GPT-5.3-Codex via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4",
        provider="openai_codex",
        name="GPT-5.4 (ChatGPT)",
        description="GPT-5.4 via ChatGPT subscription OAuth",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]

_GOOGLE_MODELS = [
    Model(
        id="gemini-2.5-flash-lite",
        provider="google",
        name="Gemini 2.5 Lite",
        description="Gemini 2.0 Flash Lite is low latancy, balanced language model from Google, designed for both text and visual inputs.",
        max_context_token=1_000_000,
        capabilities=["tool_use", "vision", "structured_output"],
        input_token_price_1m=0.1,
        output_token_price_1m=0.4,
    ),
    Model(
        id="gemini-2.5-flash",
        provider="google",
        max_context_token=1_000_000,
        name="Gemini 2.5 Flash ",
        description="Gemini 2.5 Flash is Google's first fully hybrid reasoning AI model, designed for high speed and cost-efficiency, allowing developers to toggle advanced reasoning on or off as needed.",
        capabilities=["tool_use", "vision", "thinking", "structured_output"],
        input_token_price_1m=0.3,
        output_token_price_1m=2.5,
        default=True,
    ),
    Model(
        id="gemini-2.5-pro",
        provider="google",
        name="Gemini 2.5 Pro Thinking",
        max_context_token=1_000_000,
        description="Gemini 2.5 Pro with thinking",
        capabilities=["tool_use", "thinking", "vision", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gemini-3-pro-preview",
        provider="google",
        name="Gemini 3 Pro",
        max_context_token=1_000_000,
        description="Google's most intelligent model family to date, built on a foundation of state-of-the-art reasoning",
        capabilities=["tool_use", "thinking", "vision", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        input_token_price_1m=2,
        output_token_price_1m=12,
    ),
    Model(
        id="gemini-3.1-pro-preview",
        provider="google",
        name="Gemini 3.1 Pro",
        max_context_token=1_000_000,
        description="Google's most intelligent model family to date, built on a foundation of state-of-the-art reasoning",
        capabilities=["tool_use", "thinking", "vision", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        input_token_price_1m=2,
        output_token_price_1m=12,
    ),
]

_DEEPINFRA_MODELS = [
    Model(
        id="google/gemma-4-31B-it",
        provider="deepinfra",
        name="Gemma 4 31B",
        description="Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.13,
        output_token_price_1m=0.38,
    ),
    Model(
        id="google/gemma-4-26B-A4B-it",
        provider="deepinfra",
        name="Gemma 4 26A4B",
        description="Efficient, MoE variant of Gemma 4",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        input_token_price_1m=0.08,
        output_token_price_1m=0.35,
    ),
    Model(
        id="Qwen/Qwen3.6-35B-A3B",
        provider="deepinfra",
        name="Qwen 3.6",
        description="Qwen3.6-35B-A3B is Alibaba's latest flagship Mixture-of-Experts model",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=256_000,
        force_sample_params=SampleParam(
            temperature=0.7,
            top_p=0.8,
            top_k=20,
            min_p=0.0,
            repetition_penalty=1,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.2,
        output_token_price_1m=1.00,
    ),
    Model(
        id="Qwen/Qwen3-Coder-480B-A35B-Instruct",
        provider="deepinfra",
        name="Qwen 3 Coder",
        description="Qwen3-Coder-480B-A35B-Instruct is the Qwen3's most agentic code model",
        capabilities=["tool_use", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.7, top_p=0.8, top_k=20, repetition_penalty=1.05
        ),
        input_token_price_1m=0.4,
        output_token_price_1m=1.6,
    ),
    Model(
        id="Qwen/Qwen3.5-397B-A17B",
        provider="deepinfra",
        name="Qwen 3.5 Big",
        description="Qwen3-Max",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=256_000,
        force_sample_params=SampleParam(
            temperature=0.7,
            top_p=0.8,
            top_k=20,
            min_p=0.0,
            repetition_penalty=1.0,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.54,
        output_token_price_1m=3.40,
    ),
    Model(
        id="Qwen/Qwen3-Max-Thinking",
        provider="deepinfra",
        name="Qwen 3 Max Thinking",
        default_reasoning="minimal",
        description="Qwen3 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.6, top_p=0.95, top_k=20, min_p=0.0, repetition_penalty=1.0
        ),
        max_context_token=256_000,
        input_token_price_1m=1.2,
        output_token_price_1m=6,
    ),
    Model(
        id="zai-org/GLM-5",
        provider="deepinfra",
        name="Zai GLM-5",
        description="GLM-5 is an advanced, open-source large language model designed for developers tackling the toughest challenges.",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        max_context_token=200_000,
        capabilities=["tool_use", "stream"],
        input_token_price_1m=0.8,
        output_token_price_1m=2.56,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="deepinfra",
        name="Zai GLM-5.1",
        description="GLM-5.1 is Z-AI's next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor",
        force_sample_params=SampleParam(top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.43,
        output_token_price_1m=1.75,
    ),
    Model(
        id="zai-org/GLM-4.7-Flash",
        provider="deepinfra",
        name="Zai GLM-4.7 Flash",
        description="GLM-4.7-Flash is a 30B-A3B MoE model",
        force_sample_params=SampleParam(temperature=0.7, top_p=1, top_k=40),
        capabilities=["tool_use", "stream"],
        input_token_price_1m=0.06,
        output_token_price_1m=0.4,
    ),
    Model(
        id="Qwen/Qwen3.5-27B",
        provider="deepinfra",
        name="Qwen 3.5 27B",
        description="Qwen3.5 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.7,
            top_p=0.8,
            top_k=20,
            min_p=0.0,
            repetition_penalty=1.0,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.26,
        output_token_price_1m=2.6,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V3.1-Terminus",
        provider="deepinfra",
        name="DeepSeek V3.1",
        description="DeepSeek-V3.1 is post-trained on the top of DeepSeek-V3.1-Base, which is built upon the original V3 base checkpoint through a two-phase long context extension approach",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.3,
        output_token_price_1m=1.0,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V3.2",
        provider="deepinfra",
        name="DeepSeek V3.2",
        description="DeepSeek-V3.2 is a large language model designed to harmonize high computational efficiency with strong reasoning and agentic tool-use performance",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=160_000,
        input_token_price_1m=0.26,
        output_token_price_1m=0.39,
    ),
    Model(
        id="deepseek-ai/DeepSeek-R1-0528",
        provider="deepinfra",
        name="DeepSeek R1 0528",
        description="The DeepSeek R1 model has undergone a minor version upgrade, with the current version being DeepSeek-R1-0528.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.5,
        output_token_price_1m=2.18,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="deepinfra",
        name="Kimi K2.5",
        description="Kimi K2.5 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.5,
        output_token_price_1m=2.0,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="deepinfra",
        name="Kimi K2.6",
        description="Kimi K2.6 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.75,
        output_token_price_1m=3.5,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.5",
        provider="deepinfra",
        name="MiniMax-M2.5",
        description="MiniMax-M2.5 is a Mini model built for Max coding & agentic workflows with just 10 billion activated parameters",
        capabilities=["tool_use", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=0.6),
        max_context_token=262_000,
        input_token_price_1m=0.27,
        output_token_price_1m=0.95,
    ),
]
_TOGETHER_MODELS = [
    Model(
        id="zai-org/GLM-5",
        provider="together",
        name="GLM 5 FP4",
        description="General-purpose chat model on Together AI from Z.ai",
        capabilities=["tool_use", "stream", "structured_output"],
        default=True,
        input_token_price_1m=1.0,
        output_token_price_1m=3.2,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="together",
        name="GLM 5.1 FP4",
        description="General-purpose chat model on Together AI from Z.ai",
        capabilities=["tool_use", "stream", "structured_output"],
        default=True,
        input_token_price_1m=1.4,
        output_token_price_1m=4.4,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V3.1",
        provider="together",
        name="DeepSeek V3.1",
        description="General-purpose DeepSeek chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.6,
        output_token_price_1m=1.7,
    ),
    Model(
        id="Qwen/Qwen3.5-397B-A17B",
        provider="together",
        name="Qwen 3.5 397B A17B",
        description="Large general-purpose Qwen chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.6,
        output_token_price_1m=3.6,
    ),
    Model(
        id="Qwen/Qwen3.5-9B",
        provider="together",
        name="Qwen 3.5 9B FP8",
        description="Small and efficient Qwen chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.1,
        output_token_price_1m=0.15,
    ),
    Model(
        id="google/gemma-4-31B-it",
        provider="together",
        name="Gemma 4 31B",
        description="Efficient MiniMax chat model on Together AI",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.2,
        output_token_price_1m=0.5,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.7",
        provider="together",
        name="MiniMax M2.5 FP4",
        description="Efficient MiniMax chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.3,
        output_token_price_1m=1.2,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="together",
        name="Kimi K2.5",
        description="General-purpose Moonshot AI chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.5,
        output_token_price_1m=2.8,
    ),
    Model(
        id="zai-org/GLM-4.7",
        provider="together",
        name="GLM 4.7 FP8",
        description="General-purpose GLM 4.7 chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.45,
        output_token_price_1m=2.0,
    ),
    Model(
        id="Qwen/Qwen3-Coder-Next",
        provider="together",
        name="Qwen 3 Coder Next FP8",
        description="Coding-focused Qwen model for development workflows on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=0.5,
        output_token_price_1m=1.2,
    ),
    Model(
        id="Qwen/Qwen3-Coder-480B-A35B-Instruct",
        provider="together",
        name="Qwen 3 Coder 480B A35B Instruct FP8",
        description="Flagship coding-focused Qwen instruct model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=2.0,
        output_token_price_1m=2.0,
    ),
]

_OPENCODE_GO_MODELS = [
    Model(
        id="glm-5.1",
        provider="opencode_go",
        name="GLM-5.1",
        description="OpenCode Go curated GLM-5.1 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "stream"],
        max_context_token=205_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="glm-5",
        provider="opencode_go",
        name="GLM-5",
        description="OpenCode Go curated GLM-5 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "stream"],
        max_context_token=205_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="kimi-k2.5",
        provider="opencode_go",
        name="Kimi K2.5",
        description="OpenCode Go curated Kimi K2.5 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "vision", "structured_output", "stream"],
        default=True,
        max_context_token=265_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="kimi-k2.6",
        provider="opencode_go",
        name="Kimi K2.6",
        description="OpenCode Go curated Kimi K2.6 model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "thinking", "vision", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2-pro",
        provider="opencode_go",
        name="MiMo-V2-Pro",
        description="OpenCode Go curated MiMo-V2-Pro model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "stream"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="mimo-v2-omni",
        provider="opencode_go",
        name="MiMo-V2-Omni",
        description="OpenCode Go curated MiMo-V2-Omni model over the OpenAI-compatible chat completions endpoint",
        capabilities=["tool_use", "vision", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="qwen3.5-plus",
        provider="opencode_go",
        name="Qwen3.5 Plus",
        description="OpenCode Go curated Qwen3.5 Plus model over the chat completions endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="qwen3.6-plus",
        provider="opencode_go",
        name="Qwen3.6 Plus",
        description="OpenCode Go curated Qwen3.6 Plus model over the chat completions endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="minimax-m2.7",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="MiniMax M2.7",
        description="OpenCode Go curated MiniMax M2.7 Plus model over the chat completions endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="minimax-m2.5",
        provider="opencode_go",
        service_name="opencode_anthropic",
        name="MiniMax M2.5",
        description="OpenCode Go curated MiniMax M2.5 Plus model over the chat completions endpoint",
        capabilities=["tool_use", "thinking", "structured_output", "stream"],
        max_context_token=265_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]

_GITHUB_COPILOT_MODELS = [
    Model(
        id="claude-haiku-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude 4.5 Haiku",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-2.5-pro",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 2.5 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3-pro-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3.1-pro-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3.1 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3-flash-preview",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3 Flash Preview",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-4.1",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 4.1",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="grok-code-fast-1",
        provider="github_copilot",
        service_name="github_copilot",
        name="Grok Code Fast 1",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-4o",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 4o",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.1 Codex Max",
        description="",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5-mini",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=264_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5.1",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=264_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="goldeneye-free-auto",
        provider="github_copilot",
        service_name="copilot_response",
        name="Goldeneye",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.2-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.3-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4-mini",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-mini",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="raptor-mini-tertiary",
        provider="github_copilot",
        service_name="github_copilot",
        name="Raptor mini",
        max_context_token=264_000,
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=True,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.5 (Preview)",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.7",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.7",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]
AVAILABLE_MODELS = (
    _ANTHROPIC_MODELS
    + _OPENAI_MODELS
    + _OPENAI_CODEX_MODELS
    + _GOOGLE_MODELS
    + _DEEPINFRA_MODELS
    + _TOGETHER_MODELS
    + _OPENCODE_GO_MODELS
    + _GITHUB_COPILOT_MODELS
)
