from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TokenUsage:
    """Tracks token usage across a single LLM request or session.

    Fields:
        input_tokens: Non-cached input tokens (freshly computed by the model).
        output_tokens: Output tokens generated by the model.
        cached_tokens: Input tokens served from an existing cache (billed at a discount).
        cache_creation_tokens: Input tokens written to cache on this request (billed at a
            premium). Only Anthropic reports this separately; other providers set this to 0.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cached_tokens: int = 0
    cache_creation_tokens: int = 0

    @property
    def total_input_tokens(self) -> int:
        """All input tokens including cached reads and cache writes."""
        return self.input_tokens + self.cached_tokens + self.cache_creation_tokens

    @property
    def total_tokens(self) -> int:
        """All tokens consumed (input + cached + cache writes + output)."""
        return self.total_input_tokens + self.output_tokens

    def merge(self, other: TokenUsage) -> TokenUsage:
        """Return a new TokenUsage with fields summed from self and other."""
        return TokenUsage(
            input_tokens=self.input_tokens + other.input_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
            cached_tokens=self.cached_tokens + other.cached_tokens,
            cache_creation_tokens=self.cache_creation_tokens
            + other.cache_creation_tokens,
        )

    def __add__(self, other: TokenUsage) -> TokenUsage:
        return self.merge(other)

    def __bool__(self) -> bool:
        """Truthiness based on whether any token usage is recorded."""
        return self.total_tokens > 0

    def __repr__(self) -> str:
        parts = [
            f"in={self.input_tokens}",
            f"out={self.output_tokens}",
        ]
        if self.cached_tokens:
            parts.append(f"cached={self.cached_tokens}")
        if self.cache_creation_tokens:
            parts.append(f"cache_write={self.cache_creation_tokens}")
        return f"TokenUsage({', '.join(parts)})"
