from AgentCrew.modules.llm.types import Model

GOOGLE_MODELS = [
    Model(
        id="gemma-4-31b-it",
        provider="google",
        name="Gemma 4 Densed",
        description="Gemma 4 models are multimodal, handling text and image input (with audio supported on small models) and generating text output",
        max_context_token=256_000,
        capabilities=["tool_use", "vision", "structured_output", "thinking"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemma-4-26b-a4b-it",
        provider="google",
        name="Gemma 4 MoE",
        description="Gemma 4 models are multimodal, handling text and image input (with audio supported on small models) and generating text output",
        max_context_token=256_000,
        capabilities=["tool_use", "vision", "structured_output"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-flash-lite-latest",
        provider="google",
        name="Gemini Flash Lite",
        description="Gemini Flash Lite is low latancy, balanced language model from Google, designed for both text and visual inputs.",
        max_context_token=1_000_000,
        capabilities=["tool_use", "vision", "structured_output"],
        input_token_price_1m=0.1,
        output_token_price_1m=0.4,
    ),
    Model(
        id="gemini-flash-latest",
        provider="google",
        max_context_token=1_000_000,
        name="Gemini Flash",
        description="Gemini Flash is Google's first fully hybrid reasoning AI model, designed for high speed and cost-efficiency, allowing developers to toggle advanced reasoning on or off as needed.",
        capabilities=["tool_use", "vision", "thinking", "structured_output"],
        input_token_price_1m=0.3,
        output_token_price_1m=2.5,
        default=True,
    ),
    Model(
        id="gemini-pro-latest",
        provider="google",
        name="Gemini Pro Thinking",
        max_context_token=1_000_000,
        description="Gemini 2.5 Pro with thinking",
        capabilities=["tool_use", "thinking", "vision", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
]
